import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Comment from '../components/Comments/Comment';
import ApprovalCard from '../components/ApprovalCard/ApprovalCard';
export default function Home() {

  return (
    <>
      <Head>
        <title>AfterTag</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <nav styles={styles.navbar}>
          <ul>
            <Link className={styles.navlink}  href="/blog">Blog</Link>
            <Link className={styles.navlink} href="/contact">Contact</Link>
          </ul>
      </nav>
        <h1>Home</h1>
        <div className={styles.comments}>
        <ApprovalCard>
          <Comment imgUrl="https://cdn.pixabay.com/photo/2016/03/23/04/01/woman-1274056_960_720.jpg" name='Name 1' time='Title 1'/>
        </ApprovalCard>
        <ApprovalCard>
          <Comment imgUrl="https://cdn.pixabay.com/photo/2015/01/07/16/37/wood-591631__180.jpg" name='Name 2' time='Title 2'/>
        </ApprovalCard>
        </div>
      </main>
    </>
  )
}
